name: Deploy to GCP
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Build and Push to Artifact Registry
        run: |
          # The '.' at the end is CRITICAL - it tells GCP to upload the current folder
          gcloud builds submit --project=logistic-model-deploy --tag us-central1-docker.pkg.dev/logistic-model-deploy/my-model-repo/my-api .

      - name: Deploy to Cloud Run
        - name: Build and Push to Artifact Registry
        run: |
          # We are removing the manual project flag and letting the auth-action handle it
          gcloud builds submit --tag us-central1-docker.pkg.dev/logistic-model-deploy/my-model-repo/my-api .